name: Continuous integration

on: push

jobs:
  tests:
    name: RSpec tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup application
      run: docker-compose build

    - name: Setup database
      run: docker-compose run --rm web rails db:create db:schema:load db:test:prepare

    - name: Wait for elasticsearch
      run: |
        until curl http://localhost:9200 >/dev/null 2>&1
        do
          sleep 1
          echo "Elasticsearch is not ready yet..."
        done

    - name: Run tests
      run: docker-compose run --rm web rspec

  rubocop:
    name: RuboCop Linter
    runs-on: ubuntu-latest
    steps:
    - name: RuboCop Linter Action
      uses: andrewmcodes/rubocop-linter-action@v3.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
