name: Continuous integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup application
      run: docker-compose build

    - name: Run tests
      run: docker-compose run --rm web rspec
